### ISSUE TITLE
Bibli maintenu ?

### ISSUE THREAD

**Issue by kepon85** [yoandm/phpEndi#1]
Bonjour @yoandm 

Tu as l’intention de maintenir ta librairie sur moyen/long terme ? Elle est fonctionnelle ?

J’ai des besoins de créer des factures récurrentes, je développe donc je peux le faire en PHP si ta bibliothèque fonctionne. Ce message c’est pour savoir si ça vaut le coup que j’investisse du temps de dev sur ta lib…

Au plaisir,
David

**Comment by yoandm** [comment]
Bonjour 

La dernière fois que je l'ai utilisé elle l'était mais je n'ai pas prévu spécialement de la maintenir. 

En revanche tu peux t'en servir de base et contribuer si tu le souhaites. 

L'idéal serait une véritable API Rest dans enDI. Ce serait plus pratique pour développer quelque chose avec davantage de pérennité mais pour l'instant c'est partiel. 

⁣__

Yoan De Macedo
yoandm.com​

Le 18 sept. 2024, 14:00, à 14:00, David Mercereau ***@***.***> a écrit:

**Comment by kepon85** [comment]
Ok merci pour ta réponse rapide. Je me sens pas trop de maintenir une bibl en curl et compagnie, dès que ça bouge chez Endi c'est vite le bazar à debug c'est truc là (et je suis plus admin sys que dev)

>  L'idéal serait une véritable API Rest dans enDI. Ce serait plus pratique pour développer quelque chose avec davantage de pérennité mais pour l'instant c'est partiel.

Si tu veux voter pour moi :-) c'est le sens de ma question : https://forum.endi.coop/t/api-rest-pour-joindre-endi/1672

David

**Comment by kepon85** [comment]
> L'idéal serait une véritable API Rest dans enDI. Ce serait plus pratique pour développer quelque chose avec davantage de pérennité mais pour l'instant c'est partiel.

(presque) bonne nouvelle, ça semble exister : https://forum.endi.coop/t/api-rest-pour-joindre-endi/1672/6 mais c'est pas documenté par contre :-/
